import { Injectable, Logger } from '@nestjs/common';
import { rawDb } from '../db';
import { pluginMigrations } from '@wordrhyme/db';
import { eq, and, desc, sql } from 'drizzle-orm';
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { getTableConfig, type PgTable } from 'drizzle-orm/pg-core';
import {
    createInstanceMigrationOwner,
    getPluginMigrationRecordOwnerId,
    type PluginMigrationOwner,
} from './migration-governance';

/**
 * Plugin schema export convention (used for uninstall table dropping)
 */
export interface PluginSchemaExport {
    [key: string]: unknown;
}

/**
 * PluginMigrationService - Manages plugin database migrations
 *
 * Single mode: SQL migration files (generated by drizzle-kit or hand-written)
 * located in `migrations/` directory of each plugin.
 *
 * Supports two directory formats:
 * 1. **Flat files**: `migrations/*.sql` (legacy hand-written)
 * 2. **Drizzle-kit v1**: `migrations/{tag}/migration.sql` (auto-generated)
 *
 * Developer workflow:
 *   1. Edit `schema.ts` (Drizzle pgTable definitions)
 *   2. Run `drizzle-kit generate` to produce migration SQL
 *   3. Commit generated SQL + snapshot to git
 *   4. Runtime executes pending migrations on plugin load
 */
@Injectable()
export class PluginMigrationService {
    private readonly logger = new Logger(PluginMigrationService.name);

    /**
     * Run SQL migrations for a plugin
     *
     * Discovers and executes pending migration files in order.
     * Supports both flat `.sql` files and drizzle-kit subdirectory format.
     *
     * @param pluginId - Plugin identifier
     * @param pluginDir - Path to plugin directory
 * @param owner - Migration record owner. Defaults to the current deployment instance.
     */
    async runMigrations(
        pluginId: string,
        pluginDir: string,
        owner: PluginMigrationOwner = createInstanceMigrationOwner(),
    ): Promise<void> {
        const migrationOwnerId = getPluginMigrationRecordOwnerId(owner);
        const migrationsDir = path.join(pluginDir, 'migrations');

        // Check if migrations directory exists
        try {
            await fs.access(migrationsDir);
        } catch {
            this.logger.debug(`No migrations directory for plugin ${pluginId}`);
            return;
        }

        // Discover migration files (flat + drizzle-kit subdirectory format)
        const migrationFiles = await this.discoverMigrations(migrationsDir);

        if (!migrationFiles.length) {
            return;
        }

        // Get applied migrations
        const applied = await rawDb.select()
            .from(pluginMigrations)
            .where(
                and(
                    eq(pluginMigrations.pluginId, pluginId),
                    eq(pluginMigrations.organizationId, migrationOwnerId)
                )
            )
            .orderBy(desc(pluginMigrations.appliedAt));

        const appliedNames = new Set(applied.map(m => m.migrationFile));

        // Apply pending migrations
        for (const { name, filePath } of migrationFiles) {
            if (appliedNames.has(name)) {
                continue;
            }

            const sqlContent = await fs.readFile(filePath, 'utf-8');
            const checksum = this.calculateChecksum(sqlContent);

            // Split SQL into individual statements and execute one by one
            const statements = this.splitSqlStatements(sqlContent);

            try {
                await rawDb.transaction(async (tx: any) => {
                    for (const stmt of statements) {
                        await tx.execute(sql.raw(stmt));
                    }

                    await tx.insert(pluginMigrations).values({
                        pluginId,
                        organizationId: migrationOwnerId,
                        migrationFile: name,
                        checksum,
                    });
                });

                this.logger.log(`✅ Applied migration ${name} for plugin ${pluginId}`);
            } catch (error) {
                this.logger.error(`❌ Failed to apply migration ${name}: ${error}`);
                throw error;
            }
        }
    }

    /**
     * Rollback the last migration for a plugin
     */
    async rollbackLastMigration(
        pluginId: string,
        pluginDir: string,
        owner: PluginMigrationOwner = createInstanceMigrationOwner(),
    ): Promise<boolean> {
        const migrationOwnerId = getPluginMigrationRecordOwnerId(owner);
        const [lastMigration] = await rawDb.select()
            .from(pluginMigrations)
            .where(
                and(
                    eq(pluginMigrations.pluginId, pluginId),
                    eq(pluginMigrations.organizationId, migrationOwnerId)
                )
            )
            .orderBy(desc(pluginMigrations.appliedAt))
            .limit(1);

        if (!lastMigration) {
            return false;
        }

        const rollbackFile = await this.resolveRollbackFile(pluginDir, lastMigration.migrationFile);
        if (!rollbackFile) {
            this.logger.warn(`No rollback file found for migration ${lastMigration.migrationFile}`);
            return false;
        }

        try {
            const rollbackSql = await fs.readFile(rollbackFile, 'utf-8');
            const statements = this.splitSqlStatements(rollbackSql);
            for (const stmt of statements) {
                await rawDb.execute(sql.raw(stmt));
            }

            await rawDb.delete(pluginMigrations).where(
                eq(pluginMigrations.id, lastMigration.id)
            );

            this.logger.log(`✅ Rolled back migration ${lastMigration.migrationFile}`);
            return true;
        } catch {
            this.logger.warn(`Failed to execute rollback file: ${rollbackFile}`);
            return false;
        }
    }

    /**
     * Drop all tables for a plugin (used during uninstall)
     *
     * Extracts table names from plugin's Drizzle schema export and drops them.
     * Tables are dropped in reverse order to handle FK dependencies.
     *
     * @param pluginId - Plugin identifier
     * @param schema - Plugin's exported schema object with pgTable definitions
     * @param owner - Migration record owner. Defaults to the current deployment instance.
     */
    async dropPluginTables(
        pluginId: string,
        schema: PluginSchemaExport,
        owner: PluginMigrationOwner = createInstanceMigrationOwner(),
    ): Promise<void> {
        const migrationOwnerId = getPluginMigrationRecordOwnerId(owner);
        const tableNames = this.extractTableNames(schema);

        if (!tableNames.length) {
            return;
        }

        // Drop in reverse order to handle FK dependencies
        for (const tableName of tableNames.reverse()) {
            try {
                await rawDb.execute(sql.raw(`DROP TABLE IF EXISTS "${tableName}" CASCADE`));
            } catch (error) {
                const err = error instanceof Error ? error : new Error(String(error));
                this.logger.error(`❌ Failed to drop table ${tableName} for ${pluginId}: ${err.message}`);
            }
        }

        // Remove migration records
        await rawDb.delete(pluginMigrations).where(
            and(
                eq(pluginMigrations.pluginId, pluginId),
                eq(pluginMigrations.organizationId, migrationOwnerId),
            )
        );

        this.logger.log(`🗑️ Dropped tables for ${pluginId}: ${tableNames.join(', ')}`);
    }

    /**
     * Discover migration files from a directory.
     *
     * Supports two formats:
     * 1. Flat: `*.sql` files directly in the directory
     * 2. Drizzle-kit v1: `{tag}/migration.sql` subdirectories
     *
     * Returns sorted list of { name, filePath } entries.
     */
    private async discoverMigrations(
        migrationsDir: string
    ): Promise<Array<{ name: string; filePath: string }>> {
        const entries = await fs.readdir(migrationsDir, { withFileTypes: true });
        const migrations: Array<{ name: string; filePath: string }> = [];

        for (const entry of entries) {
            if (entry.isFile() && entry.name.endsWith('.sql') && !entry.name.endsWith('.down.sql')) {
                // Flat SQL file: 001_initial.sql
                migrations.push({
                    name: entry.name,
                    filePath: path.join(migrationsDir, entry.name),
                });
            } else if (entry.isDirectory()) {
                // Drizzle-kit subdirectory: 20260324_xyz/migration.sql
                const migrationSql = path.join(migrationsDir, entry.name, 'migration.sql');
                try {
                    await fs.access(migrationSql);
                    migrations.push({
                        name: entry.name,
                        filePath: migrationSql,
                    });
                } catch {
                    // Not a migration directory (e.g., meta/), skip
                }
            }
        }

        // Sort by name (works for both 001_xxx and 20260324_xxx formats)
        return migrations.sort((a, b) => a.name.localeCompare(b.name));
    }

    /**
     * Extract table names from a plugin schema export
     */
    private extractTableNames(schema: PluginSchemaExport): string[] {
        const names: string[] = [];
        for (const value of Object.values(schema)) {
            if (this.isPgTable(value)) {
                names.push(getTableConfig(value as PgTable).name);
            }
        }
        return names;
    }

    /**
     * Check if a value is a Drizzle PgTable
     */
    private isPgTable(value: unknown): boolean {
        return (
            value !== null &&
            typeof value === 'object' &&
            Symbol.for('drizzle:Name') in (value as object)
        );
    }

    /**
     * Split SQL content into individual statements
     *
     * Handles:
     * - Semicolon-separated statements
     * - DO $$ ... $$ blocks (PL/pgSQL)
     * - Comments (-- and block comments)
     * - Drizzle-kit statement breakpoints (--\> statement-breakpoint)
     */
    private splitSqlStatements(content: string): string[] {
        const statements: string[] = [];
        let current = '';
        let inDollarBlock = false;

        const lines = content.split('\n');
        for (const line of lines) {
            const trimmed = line.trim();

            // Inside DO $$ blocks: accumulate everything (including comments)
            if (inDollarBlock) {
                current += line + '\n';
                if (trimmed.endsWith('$$;')) {
                    statements.push(current.trim());
                    current = '';
                    inDollarBlock = false;
                }
                continue;
            }

            // Skip empty lines and comments (only outside dollar blocks)
            if (!trimmed || trimmed.startsWith('--')) {
                continue;
            }

            // Detect start of DO $$ blocks
            if (trimmed.toUpperCase().startsWith('DO $$') || trimmed.toUpperCase().startsWith('DO $')) {
                inDollarBlock = true;
                current += line + '\n';
                // Check if single-line: DO $$ ... END $$;
                if (trimmed.endsWith('$$;')) {
                    statements.push(current.trim());
                    current = '';
                    inDollarBlock = false;
                }
                continue;
            }

            // Regular statement - accumulate until semicolon
            current += line + '\n';
            if (trimmed.endsWith(';')) {
                const stmt = current.trim().replace(/;$/, '');
                if (stmt) {
                    statements.push(stmt);
                }
                current = '';
            }
        }

        // Handle trailing statement without semicolon
        const remaining = current.trim().replace(/;$/, '');
        if (remaining) {
            statements.push(remaining);
        }

        return statements;
    }

    /**
     * Calculate checksum for migration content
     */
    private calculateChecksum(content: string): string {
        return crypto.createHash('sha256').update(content).digest('hex');
    }

    /**
     * Resolve rollback file for both flat-file and nested drizzle-style migrations.
     */
    private async resolveRollbackFile(
        pluginDir: string,
        migrationFile: string,
    ): Promise<string | null> {
        const migrationsDir = path.join(pluginDir, 'migrations');
        const baseName = migrationFile.replace(/\.sql$/, '');
        const candidates = migrationFile.endsWith('.sql')
            ? [
                path.join(migrationsDir, `${baseName}.down.sql`),
            ]
            : [
                path.join(migrationsDir, migrationFile, 'down.sql'),
                path.join(migrationsDir, migrationFile, 'migration.down.sql'),
                path.join(migrationsDir, migrationFile, 'rollback.sql'),
            ];

        for (const candidate of candidates) {
            try {
                await fs.access(candidate);
                return candidate;
            } catch {
                // Try next candidate
            }
        }

        return null;
    }
}
